// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTracker.Server.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieTracker.Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250109200411_changename1")]
    partial class changename1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieTracker.Server.Data.MovieEntity", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Review")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Overview = "The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.",
                            PosterPath = "https://image.tmdb.org/t/p/original//xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg",
                            Rating = 0,
                            Title = "Ad Astra"
                        },
                        new
                        {
                            MovieId = 2,
                            Overview = "After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine 'Bloodshot'. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there's more to the conspiracy than he thought.",
                            PosterPath = "https://image.tmdb.org/t/p/original//8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg",
                            Rating = 0,
                            Title = "Bloodshot"
                        },
                        new
                        {
                            MovieId = 3,
                            Overview = "In Scooby-Doos greatest adventure yet, see the never-before told story of how lifelong friends Scooby and Shaggy first met and how they joined forces with young detectives Fred, Velma, and Daphne to form the famous Mystery Inc. Now, with hundreds of cases solved, Scooby and the gang face their biggest, toughest mystery ever: an evil plot to unleash the ghost dog Cerberus upon the world. As they race to stop this global dogpocalypse, the gang discovers that Scooby has a secret legacy and an epic destiny greater than anyone ever imagined.",
                            PosterPath = "https://image.tmdb.org/t/p/original//jHo2M1OiH9Re33jYtUQdfzPeUkx.jpg",
                            Rating = 0,
                            Title = "Scoob!"
                        },
                        new
                        {
                            MovieId = 4,
                            Overview = "A disgraced doctor and his family are held hostage at their home by criminals on the run, when a robbery-gone-awry requires them to seek immediate medical attention.",
                            PosterPath = "https://image.tmdb.org/t/p/original//niyXFhGIk4W2WTcX2Eod8vx2Mfe.jpg",
                            Rating = 0,
                            Title = "Survive the Night"
                        },
                        new
                        {
                            MovieId = 5,
                            Overview = "A couple experiences a defining moment in their relationship when they are unintentionally embroiled in a murder mystery. As their journey to clear their names takes them from one extreme and hilarious - circumstance to the next, they must figure out how they, and their relationship, can survive the night.",
                            PosterPath = "https://image.tmdb.org/t/p/original//5jdLnvALCpK1NkeQU1z4YvOe2dZ.jpg",
                            Rating = 0,
                            Title = "The Lovebirds"
                        },
                        new
                        {
                            MovieId = 6,
                            Overview = "At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.",
                            PosterPath = "https://image.tmdb.org/t/p/original//iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
                            Rating = 0,
                            Title = "1917"
                        },
                        new
                        {
                            MovieId = 7,
                            Overview = "Based on the global blockbuster videogame franchise from Sega, Sonic the Hedgehog tells the story of the worlds speediest hedgehog as he embraces his new home on Earth. In this live-action adventure comedy, Sonic and his new best friend team up to defend the planet from the evil genius Dr. Robotnik and his plans for world domination.",
                            PosterPath = "https://image.tmdb.org/t/p/original//aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg",
                            Rating = 0,
                            Title = "Sonic the Hedgehog"
                        },
                        new
                        {
                            MovieId = 8,
                            Overview = "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
                            PosterPath = "https://image.tmdb.org/t/p/original//udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
                            Rating = 0,
                            Title = "Joker"
                        },
                        new
                        {
                            MovieId = 9,
                            Overview = "Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.",
                            PosterPath = "https://image.tmdb.org/t/p/original//h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
                            Rating = 0,
                            Title = "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)"
                        },
                        new
                        {
                            MovieId = 10,
                            Overview = "Marcus and Mike are forced to confront new threats, career changes, and midlife crises as they join the newly created elite team AMMO of the Miami police department to take down the ruthless Armando Armas, the vicious leader of a Miami drug cartel.",
                            PosterPath = "https://image.tmdb.org/t/p/original//y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",
                            Rating = 0,
                            Title = "Bad Boys for Life"
                        },
                        new
                        {
                            MovieId = 11,
                            Overview = "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
                            PosterPath = "https://image.tmdb.org/t/p/original//qa6HCwP4Z15l3hpsASz3auugEW6.jpg",
                            Rating = 0,
                            Title = "Cars"
                        },
                        new
                        {
                            MovieId = 12,
                            Overview = "Tyler Rake, a fearless mercenary who offers his services on the black market, embarks on a dangerous mission when he is hired to rescue the kidnapped son of a Mumbai crime lord",
                            PosterPath = "https://image.tmdb.org/t/p/original//wlfDxbGEsW58vGhFljKkcR5IxDj.jpg",
                            Rating = 0,
                            Title = "Extraction"
                        },
                        new
                        {
                            MovieId = 13,
                            Overview = "Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.",
                            PosterPath = "https://image.tmdb.org/t/p/original//pjeMs3yqRmFL3giJy4PMXWZTTPa.jpg",
                            Rating = 0,
                            Title = "Frozen II"
                        },
                        new
                        {
                            MovieId = 14,
                            Overview = "Earth is decimated after intergalactic tyrant Darkseid has devastated the Justice League in a poorly executed war by the DC Super Heroes. Now the remaining bastions of good the Justice League, Teen Titans, Suicide Squad and assorted others must regroup, strategize and take the war to Darkseid in order to save the planet and its surviving inhabitants.",
                            PosterPath = "https://image.tmdb.org/t/p/original//c01Y4suApJ1Wic2xLmaq1QYcfoZ.jpg",
                            Rating = 0,
                            Title = "Justice League Dark: Apokolips War"
                        },
                        new
                        {
                            MovieId = 15,
                            Overview = "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
                            PosterPath = "https://image.tmdb.org/t/p/original//db32LaOibwEliAmSL2jjDF6oDdj.jpg",
                            Rating = 0,
                            Title = "Star Wars: The Rise of Skywalker"
                        },
                        new
                        {
                            MovieId = 16,
                            Overview = "In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.",
                            PosterPath = "https://image.tmdb.org/t/p/original//f4aul3FyD3jv3v4bul1IrkWZvzq.jpg",
                            Rating = 0,
                            Title = "Onward"
                        },
                        new
                        {
                            MovieId = 17,
                            Overview = "A guy meets the woman of his dreams and invites her to his company's corporate retreat, but realizes he sent the invite to the wrong person.",
                            PosterPath = "https://image.tmdb.org/t/p/original//A2YlIrzypvhS3vTFMcDkG3xLvac.jpg",
                            Rating = 0,
                            Title = "The Wrong Missy"
                        },
                        new
                        {
                            MovieId = 18,
                            Overview = "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
                            PosterPath = "https://image.tmdb.org/t/p/original//9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
                            Rating = 0,
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 19,
                            Overview = "A kindhearted street urchin named Aladdin embarks on a magical adventure after finding a lamp that releases a wisecracking genie while a power-hungry Grand Vizier vies for the same lamp that has the power to make their deepest wishes come true.",
                            PosterPath = "https://image.tmdb.org/t/p/original//3iYQTLGoy7QnjcUYRJy4YrAgGvp.jpg",
                            Rating = 0,
                            Title = "Aladdin"
                        },
                        new
                        {
                            MovieId = 20,
                            Overview = "After an earthquake destroys their underwater station, six researchers must navigate two miles along the dangerous, unknown depths of the ocean floor to make it to safety in a race against time.",
                            PosterPath = "https://image.tmdb.org/t/p/original//gzlbb3yeVISpQ3REd3Ga1scWGTU.jpg",
                            Rating = 0,
                            Title = "Underwater"
                        },
                        new
                        {
                            MovieId = 21,
                            Overview = "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
                            PosterPath = "https://image.tmdb.org/t/p/original//6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
                            Rating = 0,
                            Title = "Star Wars"
                        },
                        new
                        {
                            MovieId = 22,
                            Overview = "Interstellar chronicles the adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
                            PosterPath = "https://image.tmdb.org/t/p/original//gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
                            Rating = 0,
                            Title = "Interstellar"
                        },
                        new
                        {
                            MovieId = 23,
                            Overview = "When Cecilia's abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turn lethal, Cecilia works to prove that she is being hunted by someone nobody can see.",
                            PosterPath = "https://image.tmdb.org/t/p/original//5EufsDwXdY2CVttYOk2WtYhgKpa.jpg",
                            Rating = 0,
                            Title = "The Invisible Man"
                        },
                        new
                        {
                            MovieId = 24,
                            Overview = "Fuelled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne and Diana Prince assemble a team of metahumans consisting of Barry Allen, Arthur Curry and Victor Stone to face the catastrophic threat of Steppenwolf and the Parademons who are on the hunt for three Mother Boxes on Earth.",
                            PosterPath = "https://image.tmdb.org/t/p/original//eifGNCSDuxJeS1loAXil5bIGgvC.jpg",
                            Rating = 0,
                            Title = "Justice League"
                        },
                        new
                        {
                            MovieId = 25,
                            Overview = "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
                            PosterPath = "https://image.tmdb.org/t/p/original//pThyQovXQrw2m0s9x82twj48Jq4.jpg",
                            Rating = 0,
                            Title = "Knives Out"
                        },
                        new
                        {
                            MovieId = 26,
                            Overview = "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
                            PosterPath = "https://image.tmdb.org/t/p/original//7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
                            Rating = 0,
                            Title = "Avengers: Infinity War"
                        },
                        new
                        {
                            MovieId = 27,
                            Overview = "Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub's arrival. Scar, Mufasa's brother and former heir to the throne has plans of his own. The battle for Pride Rock is ravaged with betrayal, tragedy and drama, ultimately resulting in Simba's exile. With help from a curious pair of newfound friends, Simba will have to figure out how to grow up and take back what is rightfully his.",
                            PosterPath = "https://image.tmdb.org/t/p/original//2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg",
                            Rating = 0,
                            Title = "The Lion King"
                        },
                        new
                        {
                            MovieId = 28,
                            Overview = "A World War II satire that follows a lonely German boy whose world view is turned upside down when he discovers his single mother is hiding a young Jewish girl in their attic. Aided only by his idiotic imaginary friend, Adolf Hitler, Jojo must confront his blind nationalism.",
                            PosterPath = "https://image.tmdb.org/t/p/original//7GsM4mtM0worCtIVeiQt28HieeN.jpg",
                            Rating = 0,
                            Title = "Jojo Rabbit"
                        },
                        new
                        {
                            MovieId = 29,
                            Overview = "Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
                            PosterPath = "https://image.tmdb.org/t/p/original//4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
                            Rating = 0,
                            Title = "Spider-Man: Far from Home"
                        },
                        new
                        {
                            MovieId = 30,
                            Overview = "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
                            PosterPath = "https://image.tmdb.org/t/p/original//RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
                            Rating = 0,
                            Title = "The Avengers"
                        },
                        new
                        {
                            MovieId = 31,
                            Overview = "As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the worlds most dangerous game.",
                            PosterPath = "https://image.tmdb.org/t/p/original//jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg",
                            Rating = 0,
                            Title = "Jumanji: The Next Level"
                        },
                        new
                        {
                            MovieId = 32,
                            Overview = "After losing his wife seven years earlier, the eccentric Dr. John Dolittle, famed doctor and veterinarian of Queen Victoria England, hermits himself away behind the high walls of Dolittle Manor with only his menagerie of exotic animals for company. But when the young queen falls gravely ill, a reluctant Dolittle is forced to set sail on an epic adventure to a mythical island in search of a cure, regaining his wit and courage as he crosses old adversaries and discovers wondrous creatures.",
                            PosterPath = "https://image.tmdb.org/t/p/original//xnjvwfDulnOCy8qtYX0iqydmMhk.jpg",
                            Rating = 0,
                            Title = "Dolittle"
                        },
                        new
                        {
                            MovieId = 33,
                            Overview = "The 47-year old Al Capone, after 10 years in prison, starts suffering from dementia and comes to be haunted by his violent past.",
                            PosterPath = "https://image.tmdb.org/t/p/original//75gDv38UgRtAukSxNXcjatyQmEa.jpg",
                            Rating = 0,
                            Title = "Capone"
                        },
                        new
                        {
                            MovieId = 34,
                            Overview = "Katniss Everdeen reluctantly becomes the symbol of a mass rebellion against the autocratic Capitol.",
                            PosterPath = "https://image.tmdb.org/t/p/original//4FAA18ZIja70d1Tu5hr5cj2q1sB.jpg",
                            Rating = 0,
                            Title = "The Hunger Games: Mockingjay - Part 1"
                        },
                        new
                        {
                            MovieId = 35,
                            Overview = "Immediately after the events of The Desolation of Smaug, Bilbo and the dwarves try to defend Erebor's mountain of treasure from others who claim it: the men of the ruined Laketown and the elves of Mirkwood. Meanwhile an army of Orcs led by Azog the Defiler is marching on Erebor, fueled by the rise of the dark lord Sauron. Dwarves, elves and men must unite, and the hope for Middle-Earth falls into Bilbo's hands.",
                            PosterPath = "https://image.tmdb.org/t/p/original//xT98tLqatZPQApyRmlPL12LtiWp.jpg",
                            Rating = 0,
                            Title = "The Hobbit: The Battle of the Five Armies"
                        },
                        new
                        {
                            MovieId = 36,
                            Overview = "In a future where a failed global-warming experiment kills off most life on the planet, a class system evolves aboard the Snowpiercer, a train that travels around the globe via a perpetual-motion engine.",
                            PosterPath = "https://image.tmdb.org/t/p/original//9JPx09Rr0Txq2eSQfjq1DEBR5cx.jpg",
                            Rating = 0,
                            Title = "Snowpiercer"
                        },
                        new
                        {
                            MovieId = 37,
                            Overview = "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
                            PosterPath = "https://image.tmdb.org/t/p/original//qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                            Rating = 0,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 38,
                            Overview = "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
                            PosterPath = "https://image.tmdb.org/t/p/original//gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
                            Rating = 0,
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            MovieId = 39,
                            Overview = "Buck is a big-hearted dog whose blissful domestic life is turned upside down when he is suddenly uprooted from his California home and transplanted to the exotic wilds of the Yukon during the Gold Rush of the 1890s. As the newest rookie on a mail delivery dog sled team and later its leader Buck experiences the adventure of a lifetime, ultimately finding his true place in the world and becoming his own master.",
                            PosterPath = "https://image.tmdb.org/t/p/original//33VdppGbeNxICrFUtW2WpGHvfYc.jpg",
                            Rating = 0,
                            Title = "The Call of the Wild"
                        },
                        new
                        {
                            MovieId = 40,
                            Overview = "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
                            PosterPath = "https://image.tmdb.org/t/p/original//78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
                            Rating = 0,
                            Title = "Iron Man"
                        },
                        new
                        {
                            MovieId = 41,
                            Overview = "The coach of a college tennis team is given an ultimatum: put together a winning team, or else.",
                            PosterPath = "https://image.tmdb.org/t/p/original//tgjpxqrugdbnADyKGvo65kySaBL.jpg",
                            Rating = 0,
                            Title = "Jocks"
                        },
                        new
                        {
                            MovieId = 42,
                            Overview = "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
                            PosterPath = "https://image.tmdb.org/t/p/original//c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
                            Rating = 0,
                            Title = "Spider-Man: Homecoming"
                        },
                        new
                        {
                            MovieId = 43,
                            Overview = "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.",
                            PosterPath = "https://image.tmdb.org/t/p/original//kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
                            Rating = 0,
                            Title = "Star Wars: The Last Jedi"
                        },
                        new
                        {
                            MovieId = 44,
                            Overview = "When a father is forced to abruptly depart for work, he leaves his children, Aidan and Mia, at their holiday home in the care of his new girlfriend, Grace. Isolated and alone, a blizzard traps them inside the lodge as terrifying events summon specters from Grace's dark past.",
                            PosterPath = "https://image.tmdb.org/t/p/original//yake2myhbW7c6dKbmwYDy1i40bm.jpg",
                            Rating = 0,
                            Title = "The Lodge"
                        },
                        new
                        {
                            MovieId = 45,
                            Overview = "An Amazon princess comes to the world of Man in the grips of the First World War to confront the forces of evil and bring an end to human conflict.",
                            PosterPath = "https://image.tmdb.org/t/p/original//gfJGlDaHuWimErCr5Ql0I8x9QSy.jpg",
                            Rating = 0,
                            Title = "Wonder Woman"
                        },
                        new
                        {
                            MovieId = 46,
                            Overview = "For Lieutenant Pete 'Maverick' Mitchell and his friend and co-pilot Nick 'Goose' Bradshaw, being accepted into an elite training school for fighter pilots is a dream come true. But a tragedy, as well as personal demons, will threaten Pete's dreams of becoming an ace pilot.",
                            PosterPath = "https://image.tmdb.org/t/p/original//xUuHj3CgmZQ9P2cMaqQs4J0d4Zc.jpg",
                            Rating = 0,
                            Title = "Top Gun"
                        },
                        new
                        {
                            MovieId = 47,
                            Overview = "In the year 180, the death of emperor Marcus Aurelius throws the Roman Empire into chaos.  Maximus is one of the Roman army's most capable and trusted generals and a key advisor to the emperor.  As Marcus' devious son Commodus ascends to the throne, Maximus is set to be executed.  He escapes, but is captured by slave traders.  Renamed Spaniard and forced to become a gladiator, Maximus must battle to the death with other men for the amusement of paying audiences.",
                            PosterPath = "https://image.tmdb.org/t/p/original//dvKsQB84W2Sv6s7jpGmzQBVyQe3.jpg",
                            Rating = 0,
                            Title = "Gladiator"
                        },
                        new
                        {
                            MovieId = 48,
                            Overview = "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
                            PosterPath = "https://image.tmdb.org/t/p/original//6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
                            Rating = 0,
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            MovieId = 49,
                            Overview = "A patriarch of a wealthy and powerful family suddenly passes away, leaving his wife and daughter with a shocking secret inheritance that threatens to unravel and destroy their lives.",
                            PosterPath = "https://image.tmdb.org/t/p/original//l13mt3oHErSkkqJbN1bjzgtK0Vq.jpg",
                            Rating = 0,
                            Title = "Inheritance"
                        },
                        new
                        {
                            MovieId = 50,
                            Overview = "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
                            PosterPath = "https://image.tmdb.org/t/p/original//5KCVkau1HEl7ZzfPsKAPM0sMiKc.jpg",
                            Rating = 0,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            MovieId = 51,
                            Overview = "After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.",
                            PosterPath = "https://image.tmdb.org/t/p/original//gwi5kL7HEWAOTffiA14e4SbOGra.jpg",
                            Rating = 0,
                            Title = "Doctor Strange"
                        },
                        new
                        {
                            MovieId = 52,
                            Overview = "Ever since US Diplomatic Security Service Agent Hobbs and lawless outcast Shaw first faced off, they just have swapped smacks and bad words. But when cyber-genetically enhanced anarchist Brixton's ruthless actions threaten the future of humanity, both join forces to defeat him. (A spin-off of Fate of the Furious,focusing on Johnson's Luke Hobbs and Statham's Deckard Shaw.)",
                            PosterPath = "https://image.tmdb.org/t/p/original//qRyy2UmjC5ur9bDi3kpNNRCc5nc.jpg",
                            Rating = 0,
                            Title = "Fast & Furious Presents: Hobbs & Shaw"
                        },
                        new
                        {
                            MovieId = 53,
                            Overview = "A detective suffering from a personal loss receives a call from his recently deceased niece. Being able to communicate across time, the two work together to try and stop the crime before it occurs.",
                            PosterPath = "https://image.tmdb.org/t/p/original//uNHueGo5TYCTLzoGULse65GC32Q.jpg",
                            Rating = 0,
                            Title = "Don't Let Go"
                        },
                        new
                        {
                            MovieId = 54,
                            Overview = "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
                            PosterPath = "https://image.tmdb.org/t/p/original//f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
                            Rating = 0,
                            Title = "The Matrix"
                        },
                        new
                        {
                            MovieId = 55,
                            Overview = "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
                            PosterPath = "https://image.tmdb.org/t/p/original//oZRVDpNtmHk8M1VYy1aeOWUXgbC.jpg",
                            Rating = 0,
                            Title = "Terminator Genisys"
                        },
                        new
                        {
                            MovieId = 56,
                            Overview = "Young princess Anna of Arendelle dreams about finding true love at her sister Elsas coronation. Fate takes her on a dangerous journey in an attempt to end the eternal winter that has fallen over the kingdom. She's accompanied by ice delivery man Kristoff, his reindeer Sven, and snowman Olaf. On an adventure where she will find out what friendship, courage, family, and true love really means.",
                            PosterPath = "https://image.tmdb.org/t/p/original//yald8Lsb4uCRvjIH3spzR84Kdwf.jpg",
                            Rating = 0,
                            Title = "Frozen"
                        },
                        new
                        {
                            MovieId = 57,
                            Overview = "Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.",
                            PosterPath = "https://image.tmdb.org/t/p/original//A6BCtWOv5R1X6DmklAuSM6OxnL9.jpg",
                            Rating = 0,
                            Title = "Captain America: Civil War"
                        },
                        new
                        {
                            MovieId = 58,
                            Overview = "In the last months of World War II, as the Allies make their final push in the European theatre, a battle-hardened U.S. Army sergeant named 'Wardaddy' commands a Sherman tank called 'Fury' and its five-man crew on a deadly mission behind enemy lines. Outnumbered and outgunned, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.",
                            PosterPath = "https://image.tmdb.org/t/p/original//pfte7wdMobMF4CVHuOxyu6oqeeA.jpg",
                            Rating = 0,
                            Title = "Fury"
                        },
                        new
                        {
                            MovieId = 59,
                            Overview = "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of an all-powerful new threat, the ruthless Hela.",
                            PosterPath = "https://image.tmdb.org/t/p/original//rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
                            Rating = 0,
                            Title = "Thor: Ragnarok"
                        },
                        new
                        {
                            MovieId = 60,
                            Overview = "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren't prepared for the madness that lurks within.",
                            PosterPath = "https://image.tmdb.org/t/p/original//b6ko0IKC8MdYBBPkkA1aBPLe2yz.jpg",
                            Rating = 0,
                            Title = "The Shining"
                        },
                        new
                        {
                            MovieId = 61,
                            Overview = "Ray Ferrier is a divorced dockworker and less-than-perfect father. Soon after his ex-wife and her new husband drop off his teenage son and young daughter for a rare weekend visit, a strange and powerful lightning storm touches down.",
                            PosterPath = "https://image.tmdb.org/t/p/original//6Biy7R9LfumYshur3YKhpj56MpB.jpg",
                            Rating = 0,
                            Title = "War of the Worlds"
                        },
                        new
                        {
                            MovieId = 62,
                            Overview = "Vlad Tepes is a great hero, but when he learns the Sultan is preparing for battle and needs to form an army of 1,000 boys, he vows to find a way to protect his family. Vlad turns to dark forces in order to get the power to destroy his enemies and agrees to go from hero to monster as he's turned into the mythological vampire, Dracula.",
                            PosterPath = "https://image.tmdb.org/t/p/original//m5h3NtZ2ZfryIHl1MvatmANvIqQ.jpg",
                            Rating = 0,
                            Title = "Dracula Untold"
                        },
                        new
                        {
                            MovieId = 63,
                            Overview = "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
                            PosterPath = "https://image.tmdb.org/t/p/original//or06FN3Dka5tukK1e9sl16pB3iy.jpg",
                            Rating = 0,
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            MovieId = 64,
                            Overview = "Twelve strangers wake up in a clearing. They don't know where they are or how they got there. In the shadow of a dark internet conspiracy theory, ruthless elitists gather at a remote location to hunt humans for sport. But their master plan is about to be derailed when one of the hunted turns the tables on her pursuers.",
                            PosterPath = "https://image.tmdb.org/t/p/original//wxPhn4ef1EAo5njxwBkAEVrlJJG.jpg",
                            Rating = 0,
                            Title = "The Hunt"
                        },
                        new
                        {
                            MovieId = 65,
                            Overview = "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
                            PosterPath = "https://image.tmdb.org/t/p/original//rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
                            Rating = 0,
                            Title = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            MovieId = 66,
                            Overview = "American car designer Carroll Shelby and the British-born driver Ken Miles work together to battle corporate interference, the laws of physics, and their own personal demons to build a revolutionary race car for Ford Motor Company and take on the dominating race cars of Enzo Ferrari at the 24 Hours of Le Mans in France in 1966.",
                            PosterPath = "https://image.tmdb.org/t/p/original//6ApDtO7xaWAfPqfi2IARXIzj8QS.jpg",
                            Rating = 0,
                            Title = "Ford v Ferrari"
                        },
                        new
                        {
                            MovieId = 67,
                            Overview = "While trying to make his sister's wedding day go smoothly, Jack finds himself juggling an angry ex-girlfriend, an uninvited guest with a secret, a misplaced sleep sedative, and the girl that got away in alternate versions of the same day.",
                            PosterPath = "https://image.tmdb.org/t/p/original//zn7feouGPU8sELez4qvpp0EtgeQ.jpg",
                            Rating = 0,
                            Title = "Love Wedding Repeat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
